[package]
name = "rusty"
version = "0.1.0"
edition = "2021"
authors = ["Chandler Harrison <chandler.harrison@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.188"
serde_derive = "1.0.188"
toml = "0.8.2"
